[build-system]
requires = [
    "setuptools>=30.3.0",
    "wheel",
]

[tool.black]
line-length = 79
target-version = ['py37']
skip-string-normalization = true

[tool.docformatter]
recursive = true
wrap-summaries = 95
